import {
  CreditCard,
  Megaphone,
  MessageSquare,
  FileSearch,
  FileText,
  Search,
  Bookmark,
  Building2,
  Eye,
  Users,
} from "lucide-react";
import type { NavSection, Grant } from "@/types/grant";

/** Mock account identity — the live account's real name/team are NOT copied. */
export const USER = { name: "김연구", initial: "김" };
export const TEAM = { name: "김연구의 팀", plan: "Free" };

export const NAV_SECTIONS: NavSection[] = [
  {
    title: "파트너 매칭",
    links: [
      { label: "프로젝트 공고", icon: Megaphone, href: "#", external: true },
      { label: "파트너 매칭 문의", icon: MessageSquare, href: "#", external: true },
    ],
  },
  {
    title: "정부과제 수주",
    links: [
      { label: "정부과제 추천", icon: FileSearch, href: "#", active: true },
      { label: "정부과제 검색", icon: FileText, href: "#" },
      { label: "과제 수주 문의", icon: MessageSquare, href: "#", external: true },
    ],
  },
  {
    title: "연구실",
    links: [
      { label: "연구실 검색", icon: Search, href: "#" },
      { label: "저장한 연구실", icon: Bookmark, href: "#" },
    ],
  },
  {
    title: "기업",
    links: [
      { label: "AI 기반 기업 서칭", icon: Building2, href: "#" },
      { label: "열람 기업", icon: Eye, href: "#" },
      { label: "팀-플랜 관리", icon: Users, href: "#" },
    ],
  },
];

export const PLAN_LINK = { label: "서비스 플랜", icon: CreditCard, href: "#" };

export const TOTAL_COUNT = 40;
export const SORTS = ["최신 등록 순", "추천 컨설팅 순", "마감 임박 순"];

/** Mock grant listings — representative, not the account's real recommendations. */
export const NEW_ALERT_GRANT: Grant = {
  id: "g-new",
  isNew: true,
  deadlineNote: "별도 공지 시까지",
  title: "2026년 그린바이오 소재 첨단분석시스템 활성화 지원사업(장비 활용)",
  noticeName: "2026년 그린바이오 소재 첨단분석시스템 활성화 지원사업(장비 활용) 수혜기업 모집 공고",
  period: "- ~ -",
  amount: "5,000만 원",
  ministry: "경상북도",
  agency: "포항테크노파크",
  registeredAt: "2026-07-13",
  matchScore: 4,
  matchTotal: 4,
  orgTypes: "대기업, 중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관, 의료기관",
  regions: "전국",
  revenue: "-/-",
  lab: "불필요",
  tags: ["바이오소재·의료소재", "바이오파운드리 장비활용", "항체·유전자 기반 바이오소재 분석"],
};

export const GRANTS: Grant[] = [
  {
    id: "g-1",
    isNew: false,
    deadlineNote: "2026-07-08 ~ 2026-07-22",
    title: "바이오 플러스식 내구성 향상 유해 반응성 정가에 제조 기술 개발",
    noticeName: "2026년도 중소기업 기술혁신개발사업(수출지향형) 신규지원 대상과제 공고",
    period: "2026-07-08 ~ 2026-07-22",
    amount: "10억 원",
    ministry: "중소벤처기업부",
    agency: "중소기업기술정보진흥원",
    registeredAt: "2026-06-22",
    matchScore: 4,
    matchTotal: 4,
    orgTypes: "대기업, 중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관, 의료기관",
    regions: "전국",
    revenue: "-/1년 이내",
    lab: "불필요",
    tags: ["소재·부품·장비", "바이오공정", "유해 반응성 정가"],
  },
  {
    id: "g-2",
    isNew: false,
    deadlineNote: "~ 2026-07-22",
    title: "나노 인공지능 기반 생체 반응 증강 가능성 3D 프린팅 소재 맞춤 및 공정 중점 기술 개발",
    noticeName: "2026년 소재부품 미래 기술개발 사업 신규지원 대상과제 공고",
    period: "- ~ 2026-07-23",
    amount: "-",
    ministry: "과학기술정보통신부",
    agency: "국가과학기술연구회",
    registeredAt: "2026-07-13",
    matchScore: 3,
    matchTotal: 4,
    orgTypes: "중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관",
    regions: "전국",
    revenue: "-/-",
    lab: "필요",
    tags: ["나노 기술", "3D 프린팅", "인공지능 소재"],
  },
  {
    id: "g-3",
    isNew: false,
    deadlineNote: "~ 2026-07-30",
    title: "마이크로파 대역 Ku·W 대역 전자파 산란 측정 자성체 합성의 분무 건조 기반 제조 공정 기술 개발",
    noticeName: "2026년 소재 기술개발사업 신규과제 선정계획 공고",
    period: "- ~ 2026-07-30",
    amount: "-",
    ministry: "과학기술정보통신부",
    agency: "한국연구재단",
    registeredAt: "2026-07-10",
    matchScore: 4,
    matchTotal: 4,
    orgTypes: "대기업, 중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관",
    regions: "전국",
    revenue: "-/-",
    lab: "불필요",
    tags: ["자성체 소재", "전자파 차폐", "분무 건조 공정"],
  },
  {
    id: "g-4",
    isNew: false,
    deadlineNote: "~ 2026-07-30",
    title: "극한 흡착 폐수의 분산율 위한 초경량 고강도 그래핀·아라미드 복합직물 및 대면적 공정 기술 개발",
    noticeName: "2026년 탄소소재 융복합 기술개발 사업 신규지원 공고",
    period: "- ~ 2026-07-30",
    amount: "-",
    ministry: "과학기술정보통신부",
    agency: "한국연구재단",
    registeredAt: "2026-07-10",
    matchScore: 4,
    matchTotal: 4,
    orgTypes: "대기업, 중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관",
    regions: "전국",
    revenue: "-/-",
    lab: "불필요",
    tags: ["고분자 소재", "그래핀 복합재", "초경량 고강도"],
  },
  {
    id: "g-5",
    isNew: false,
    deadlineNote: "2026-07-08 ~ 2026-07-22",
    title: "국산기 고함유 EBA 기반 컴팬디파 복합 소재 기술개발 및 케이블 시제품 실증연구",
    noticeName: "2026년도 중소기업 기술혁신개발사업 신규지원 대상과제 공고",
    period: "2026-07-08 ~ 2026-07-22",
    amount: "10억 원",
    ministry: "중소벤처기업부",
    agency: "중소기업기술정보진흥원",
    registeredAt: "2026-06-22",
    matchScore: 4,
    matchTotal: 4,
    orgTypes: "중견기업, 중소기업, 대학 연구실, 국공립/민간 연구기관",
    regions: "전국",
    revenue: "-/-",
    lab: "불필요",
    tags: ["고분자 소재", "EBA 복합재", "케이블 실증"],
  },
  {
    id: "g-6",
    isNew: false,
    deadlineNote: "~ 2026-07-30",
    title: "탄소 유지 회밀활의 분자 변환과 응용에 관한 연구",
    noticeName: "2026년 기초연구사업 신규과제 선정계획 공고",
    period: "- ~ 2026-07-23",
    amount: "-",
    ministry: "과학기술정보통신부",
    agency: "한국연구재단",
    registeredAt: "2026-07-13",
    matchScore: 3,
    matchTotal: 4,
    orgTypes: "대학 연구실, 국공립/민간 연구기관",
    regions: "전국",
    revenue: "-/-",
    lab: "필요",
    tags: ["기초연구", "분자 변환", "탄소 소재"],
  },
];
